### ISSUE TITLE
Add support for application switch through `Super + mouse click`

### ISSUE THREAD

**Issue by MobCode100** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#10] opened 2022-12-14 07:19 UTC
Hi developer, thank you very much for your work. This extension works very well, but only when using alt tab keys. But using super key and mouse click, the bug happens again. I found this disturbing as mostly I tend to use super key to switch applications. Is fix going to be included in this extension?

The problem happens on Fedora 36 and also Fedora 37 (GNOME 43). Thanks again for your time.

**Comment by lucasresck** [comment] 2022-12-15 16:02
Hi, @MobCode100, thanks for your feedback. I can confirm that, in fact, when pressing the Super key and clicking on the window with the mouse pointer the bug still happens. Ubuntu 22.04 with GNOME 42.5.

Although this is not the main goal of the extension, this is obviously related because this is the same bug (scroll issue) in a similar context (application switch).

Even though we are dealing with a bug probably from GNOME or Electron, this is not a bug from the extension, so I'll mark it as an enhancement. This feature won't be prioritized, but I hope I or anyone else will take a look into this in the near future.

I also invite you into this. As a direction, if I may, I would recommend taking a look at the way the two inherited classes in [extension.js](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/blob/fede46dd2fb6fbd2368ca441754da87130c7e55e/extension.js) relate to the [js/ui/altTab.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/022c64961c22afcfe865186b5e190a7c9446ff15/js/ui/altTab.js) file of `gnome-shell`. Probably, it is necessary to find a similar behavior but in a sibling file.

Thanks again for this issue!

**Comment by MobCode100** [comment] 2022-12-15 16:12
Thanks for your attention, and the good comment. I'll take a look at the code when I have free time  😁👍. It would be nice if this can be fixed.

**Comment by holypeachy** [comment] 2023-09-09 03:35
I noticed this issue as well. It seems to happen only with VS Code though, as in, the scrolling happens when I switch back to VS Code.

**Comment by lucasresck** [comment] 2023-11-05 22:20
Hi there!

A similar bug (hot corner + mouse click) has been identified and a solution has been suggested at https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/24. The root of the problem may be the same of this issue.

https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/24 will probably be solved before the release of extension's version `v5` (GNOME 45) --- the solution is also presented with the issue --- but it may also be solved for GNOME <= 44.

Let's keep in touch!

**Comment by lucasresck** [comment] 2023-11-06 01:13
I have just created a PR with a solution to this! If you're running GNOME 45, you can test it: https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/25.

**Comment by lucasresck** [comment] 2023-11-12 18:24
Happy to share that https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/25 was merged!

I'll then close this issue and create a new issue to approach GNOME <= 44 only.

Thanks everyone!

**Closed as completed by lucasresck** 2023-11-12 18:24 UTC
Labels: bug, enhancement
